### ISSUE TITLE
stringprep produces strings with extra null characters appended

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DanielOaks/go-idn#5]
```
What steps will reproduce the problem?

str := "user"
if str != stringprep.Nodeprep(str) {
    t.Fail()
}

What is the expected output? What do you see instead?

If you look at the output byte-by-byte, it contains 3*len(str) null characters 
appended to the end of the string.

What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `chris.jo...@gmail.com` on 31 Jan 2012 at 5:00

**Comment by DanielOaks** [comment]
This happens due to the `output` slice being defined with the same size as the input on `map_table`.

https://github.com/DanielOaks/go-idn/commit/0f85ae0bb5f673890369c971592921f2b326d448#diff-ad1b10b2fc222f8be869bb048b1ad056R69 fixes this, but we ripped out that variable entirely in https://github.com/DanielOaks/go-idn/commit/21fc37ad99df0f0fdfc10dea6b6bdbc200479e80 and https://github.com/DanielOaks/go-idn/commit/e20281dcaf8c90dc8673ead645764a5e0f4822a5 in order to better support when `output` actually becomes larger than `input` was. This issue is resolved.
